### PR TITLE
Add clarification for Jambalaya logo

### PR DESCRIPTION
**Pull request by RCdeWit**
To make sure there are no misunderstandings around the apparent chicken legs in the logo.

### CODE REVIEW

**Review by jellebouwman — APPROVED** [review]
LGTM, as a followup can we link to a recipe?

**Comment by RCdeWit** [comment]
Could you please open a new ticket for the recipe?

**Comment by jellebouwman** [comment]
No I can't, because there is no issue board in this repo.

**Comment by RCdeWit** [comment]
I have enabled them; you now have issues. ✨

**Pull request merged**
